use_frameworks!

platform :ios, '9.0'

target 'CircleLoadingViewPod_Example' do
  pod 'CircleLoadingViewPod', :path => '../'

  target 'CircleLoadingViewPod_Tests' do
    inherit! :search_paths

    
  end
end
